# Generated by Django 2.1.1 on 2018-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
