# Generated by Django 2.1.1 on 2018-09-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
