# Generated by Django 2.0.5 on 2018-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='due',
            field=models.DateField(),
        ),
    ]
